on:
  - push
  - pull_request

env:
  GH_TOKEN: ${{ github.token }}
  SOPS_AGE_KEY: ${{ vars.SOPS_AGE_KEY }}

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install sops
        run: gh release download -R mozilla/sops --pattern "*.linux.amd64" --output sops --clobber && chmod +x sops

      - name: Install packages
        run: sudo apt install -y age

      - name: Generate wrangler config
        run: node scripts/generate-wrangler.js

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
